import pandas as pd
s1 = pd.Series([4, -15, 7, 7, 2, 2, 0, 0, 4])
print(s1.rank())
print("---" * 30)
print(s1.rank(method='first'))
print("---" * 30)
print(s1.rank(method='max'))
print("---" * 30)
print(s1.rank(method='min'))
print("---" * 30)
print(s1.rank(ascending=False))
print("---" * 30)
print(s1.rank(ascending=False, method='first'))
print("---" * 30)
print(s1.rank(ascending=False, method='min'))
print("---" * 30)
print(s1.rank(ascending=False, method='max'))
